#!/bin/sh

set -o errexit
set -o nounset

postgres_ready() {
    python <<END
import sys

import psycopg2

try:
    psycopg2.connect(
        dbname="postgres",
        user="${POSTGRES_USER}",
        password="${POSTGRES_PASSWORD}",
        host="${POSTGRES_HOST}",
        port="${POSTGRES_PORT}",
    )
except psycopg2.OperationalError:
    sys.exit(-1)
sys.exit(0)

END
}
until postgres_ready; do
    echo >&2 'Waiting for PostgreSQL to become available...'
    sleep 1
done

echo >&2 'PostgreSQL is available'

# this exec "$@" basically takes any command line arguments passed
# to entrypoint.sh and execs them as a command. The intention is
# basically "Do everything in this .sh script, then in the same shell
# run the command the user passes in on the command line"
exec "$@"